name: Deploy POC

on:
  workflow_dispatch:
    inputs:
      imageTag:
        type: text
      appName:
        type: text
        default: contoso
        required: true
      location:
        type: choice
        required: true
        default: canadacentral
        options:
          - asia
          - asiapacific
          - australia
          - australiacentral
          - australiacentral2
          - australiaeast
          - australiasoutheast
          - brazil
          - brazilsouth
          - brazilsoutheast
          - canada
          - canadacentral
          - canadaeast
          - centralindia
          - centralus
          - centraluseuap
          - centralusstage
          - eastasia
          - eastasiastage
          - eastus
          - eastus2
          - eastus2euap
          - eastus2stage
          - eastusstage
          - europe
          - france
          - francecentral
          - francesouth
          - germany
          - germanynorth
          - germanywestcentral
          - global
          - india
          - japan
          - japaneast
          - japanwest
          - jioindiacentral
          - jioindiawest
          - korea
          - koreacentral
          - koreasouth
          - northcentralus
          - northcentralusstage
          - northeurope
          - norway
          - norwayeast
          - norwaywest
          - southafrica
          - southafricanorth
          - southafricawest
          - southcentralus
          - southcentralusstage
          - southeastasia
          - southeastasiastage
          - southindia
          - swedencentral
          - switzerland
          - switzerlandnorth
          - switzerlandwest
          - uae
          - uaecentral
          - uaenorth
          - uk
          - uksouth
          - ukwest
          - unitedstates
          - unitedstateseuap
          - westcentralus
          - westeurope
          - westindia
          - westus
          - westus2
          - westus2stage
          - westus3
          - westusstage

env:
  APP_NAME: ${{ github.event.inputs.appName }} 
  LOCATION: ${{ github.event.inputs.location }}
  IMAGE_TAG: ${{ github.event.inputs.imageTag }}
  DEPLOYMENT_NAME: "pocdeployment"
jobs:
  deploy-poc:
    name: Deploy base infrastructure
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Generate unique deployment name
      run: echo "DEPLOYMENT_NAME=$env:DEPLOYMENT_NAME-$((New-Guid).Guid)" >> $env:GITHUB_ENV
    - name: Deploy acr and storage account
      id: deploy_infra
      uses: Azure/arm-deploy@v1.0.6
      with:
        region: ${{ env.LOCATION }}
        scope: 'subscription'
        template: ./deploy/infra/infra.bicep
        deploymentName: ${{ env.DEPLOYMENT_NAME }}
        # Supply deployment parameter values.
        parameters: appName=${{ env.APP_NAME }} location=${{ env.LOCATION }} deploymentName=${{ env.DEPLOYMENT_NAME }}
    - name: Parse '${{ env.DEPLOYMENT_NAME }}' deployment outputs
      id: deploy_infra_outputs
      run: |
        echo "::set-output name=acr::${{ fromJson($(az deployment sub show -n ${{ env.DEPLOYMENT_NAME }} --query properties.outputs.acr.value)) }}"
        echo "::set-output name=rg::$(az deployment sub show -n ${{ env.DEPLOYMENT_NAME }} --query properties.outputs.rg.value)"
        echo "::set-output name=storage::$(az deployment sub show -n ${{ env.DEPLOYMENT_NAME }} --query properties.outputs.storage.value)"
    - name: Assign service principal to acr
      run: az role assignment create --assignee ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} --scope "${{ steps.deploy_infra_outputs.outputs.acr.id }}" --role acrpull
    - name: Login to acr
      run: az acr login --name ${{ steps.deploy_infra_outputs.outputs.acr.name }}
    - name: Validate image tag
      if: ${{ env.IMAGE_TAG }} == ""
      run: echo "IMAGE_TAG=$env:GITHUB_SHA" >> $env:GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
    - name: Push the Docker image to acr
      run: docker push ${{ steps.deploy_infra_outputs.outputs.acr.loginServer }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
